#!/bin/sh
#
# Refresh the stack based on local changes.
#

# Abort on first error.
set -e

PROGNAME="${0##*/}"
PROGDIR="${0%/*}"
cd "${PROGDIR}"

# Some simple steps:
# 1a. Build everything (docker containers).
# 1b. "up" the stack, which will restart changed images.
docker-compose -f docker-compose-simple-webapp.yml up --build --detach
