#!/bin/sh
#
# Refresh the stack based on local changes.
#

# Abort on first error.
set -e

PROGNAME="${0##*/}"
PROGDIR="${0%/*}"
cd "${PROGDIR}"

# Some simple steps:
# 1a. Build spark project
# 2a. Build everything else (docker containers).
# 2b. "up" the stack, which will restart changed images.
(cd spark-container/streaming && sbt assembly)
docker-compose up --build --detach
