#!/bin/sh
#
# Refresh the stack based on local changes.
#

# Abort on first error.
set -e

PROGNAME="${0##*/}"
PROGDIR="${0%/*}"
cd "${PROGDIR}"

# Some simple steps:
# 1. Bring down all services
docker-compose -f docker-compose-simple-webapp.yml down
