apiVersion: v1
kind: Service
metadata:
  name: clickstream-analyzer
  labels:
    app: clickstream-analyzer
spec:
  ports:
  - name: "7077"
    port: 7077
    targetPort: 7077
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "18080"
    port: 18080
    targetPort: 18080
  selector:
    app: clickstream-analyzer
